/*
 * Copyright (C) 2025-2026 brick.credit
 * https://github.com/brick-dot-credit/brick-contracts
 *
 * This file is derived from the Ultrachess project under the Apache 2.0 license.
 * Copyright (C) 2022-2023 Ultrachess team
 *
 * SPDX-License-Identifier: GPL-3.0-or-later AND Apache-2.0
 * See the file LICENSE.txt for more information.
 */

// Contract names
const DEFI_MANAGER_CONTRACT: string = "DeFiManager";
const DUTCH_AUCTION_CONTRACT: string = "DutchAuction";
const ERC20_INTEREST_FARM_CONTRACT: string = "ERC20InterestFarm";
const LIQUIDITY_FORGE_CONTRACT: string = "LiquidityForge";
const LPNFT_CONTRACT: string = "LPNFT";
const LPNFT_STAKE_FARM_CONTRACT: string = "LPNFTStakeFarm";
const LPYIELD_TOKEN_CONTRACT: string = "LPYIELD";
const LPBORROW_TOKEN_CONTRACT: string = "LPBORROW";
const LPSFT_CONTRACT: string = "LPSFT";
const LPSFT_LEND_FARM_CONTRACT: string = "LPSFTLendFarm";
const MARKET_STABLE_SWAPPER_CONTRACT: string = "MarketStableSwapper";
const NOLPSFT_CONTRACT: string = "NOLPSFT";
const DEBT_TOKEN_CONTRACT = "DEBT";
const POW1_MARKET_POOLER_CONTRACT: string = "POW1MarketPooler";
const POW1_MARKET_SWAPPER_CONTRACT: string = "POW1MarketSwapper";
const POW1_TOKEN_CONTRACT: string = "POW1";
const POW5_STABLE_POOLER_CONTRACT: string = "POW5StablePooler";
const POW5_STABLE_SWAPPER_CONTRACT: string = "POW5StableSwapper";
const POW5_TOKEN_CONTRACT: string = "POW5";
const REVERSE_REPO_CONTRACT: string = "ReverseRepo";
const THE_RESERVE_CONTRACT: string = "TheReserve";
const UNI_V3_POOL_FACTORY_CONTRACT: string = "UniV3PoolFactory";
const UNIV3_STAKE_FARM_CONTRACT: string = "UniV3StakeFarm";
const YIELD_HARVEST_CONTRACT: string = "YieldHarvest";

// Deployed contract aliases
const POW1_LPNFT_STAKE_FARM_CONTRACT: string = "POW1LpNftStakeFarm";
const POW1_LPSFT_LEND_FARM_CONTRACT: string = "POW1LpSftLendFarm";
const POW1_MARKET_POOL_CONTRACT: string = "POW1Pool";
const POW1_MARKET_POOL_FACTORY_CONTRACT: string = "POW1PoolFactory";
const POW5_INTEREST_FARM_CONTRACT: string = "POW5InterestFarm";
const POW5_LPNFT_STAKE_FARM_CONTRACT: string = "POW5LpNftStakeFarm";
const POW5_LPSFT_LEND_FARM_CONTRACT: string = "POW5LpSftLendFarm";
const POW5_STABLE_POOL_CONTRACT: string = "POW5Pool";
const POW5_STABLE_POOL_FACTORY_CONTRACT: string = "POW5PoolFactory";

export {
  DEFI_MANAGER_CONTRACT,
  DUTCH_AUCTION_CONTRACT,
  ERC20_INTEREST_FARM_CONTRACT,
  LIQUIDITY_FORGE_CONTRACT,
  LPNFT_CONTRACT,
  LPNFT_STAKE_FARM_CONTRACT,
  LPYIELD_TOKEN_CONTRACT,
  LPBORROW_TOKEN_CONTRACT,
  LPSFT_CONTRACT,
  LPSFT_LEND_FARM_CONTRACT,
  MARKET_STABLE_SWAPPER_CONTRACT,
  NOLPSFT_CONTRACT,
  DEBT_TOKEN_CONTRACT,
  POW1_LPNFT_STAKE_FARM_CONTRACT,
  POW1_LPSFT_LEND_FARM_CONTRACT,
  POW1_MARKET_POOL_CONTRACT,
  POW1_MARKET_POOL_FACTORY_CONTRACT,
  POW1_MARKET_POOLER_CONTRACT,
  POW1_MARKET_SWAPPER_CONTRACT,
  POW1_TOKEN_CONTRACT,
  POW5_INTEREST_FARM_CONTRACT,
  POW5_LPNFT_STAKE_FARM_CONTRACT,
  POW5_LPSFT_LEND_FARM_CONTRACT,
  POW5_STABLE_POOL_CONTRACT,
  POW5_STABLE_POOL_FACTORY_CONTRACT,
  POW5_STABLE_POOLER_CONTRACT,
  POW5_STABLE_SWAPPER_CONTRACT,
  POW5_TOKEN_CONTRACT,
  REVERSE_REPO_CONTRACT,
  THE_RESERVE_CONTRACT,
  UNI_V3_POOL_FACTORY_CONTRACT,
  UNIV3_STAKE_FARM_CONTRACT,
  YIELD_HARVEST_CONTRACT,
};
