/*
 * Copyright (C) 2025-2026 brick.credit
 * https://github.com/brick-dot-credit/brick-contracts
 *
 * This file is derived from the Ultrachess project under the Apache 2.0 license.
 * Copyright (C) 2022-2023 Ultrachess team
 *
 * SPDX-License-Identifier: GPL-3.0-or-later AND Apache-2.0
 * See the file LICENSE.txt for more information.
 */

// Contract names
const DEFI_MANAGER_CONTRACT: string = "DeFiManager";
const DUTCH_AUCTION_CONTRACT: string = "DutchAuction";
const ERC20_INTEREST_FARM_CONTRACT: string = "ERC20InterestFarm";
const LIQUIDITY_FORGE_CONTRACT: string = "LiquidityForge";
const LPNFT_CONTRACT: string = "LPNFT";
const LPNFT_STAKE_FARM_CONTRACT: string = "LPNFTStakeFarm";
const LPYIELD_TOKEN_CONTRACT: string = "LPYIELD";
const LPBORROW_TOKEN_CONTRACT: string = "LPBORROW";
const LPSFT_CONTRACT: string = "LPSFT";
const LPSFT_LEND_FARM_CONTRACT: string = "LPSFTLendFarm";
const MARKET_STABLE_SWAPPER_CONTRACT: string = "MarketStableSwapper";
const NOLPSFT_CONTRACT: string = "NOLPSFT";
const DEBT_TOKEN_CONTRACT = "DEBT";
const YIELD_MARKET_POOLER_CONTRACT: string = "YIELDMarketPooler";
const YIELD_MARKET_SWAPPER_CONTRACT: string = "YIELDMarketSwapper";
const YIELD_TOKEN_CONTRACT: string = "YIELD";
const BORROW_STABLE_POOLER_CONTRACT: string = "BORROWStablePooler";
const BORROW_STABLE_SWAPPER_CONTRACT: string = "BORROWStableSwapper";
const BORROW_TOKEN_CONTRACT: string = "BORROW";
const REVERSE_REPO_CONTRACT: string = "ReverseRepo";
const THE_RESERVE_CONTRACT: string = "TheReserve";
const UNI_V3_POOL_FACTORY_CONTRACT: string = "UniV3PoolFactory";
const UNIV3_STAKE_FARM_CONTRACT: string = "UniV3StakeFarm";
const YIELD_HARVEST_CONTRACT: string = "YieldHarvest";

// Deployed contract aliases
const YIELD_LPNFT_STAKE_FARM_CONTRACT: string = "YIELDLpNftStakeFarm";
const YIELD_LPSFT_LEND_FARM_CONTRACT: string = "YIELDLpSftLendFarm";
const YIELD_MARKET_POOL_CONTRACT: string = "YIELDPool";
const YIELD_MARKET_POOL_FACTORY_CONTRACT: string = "YIELDPoolFactory";
const BORROW_INTEREST_FARM_CONTRACT: string = "BORROWInterestFarm";
const BORROW_LPNFT_STAKE_FARM_CONTRACT: string = "BORROWLpNftStakeFarm";
const BORROW_LPSFT_LEND_FARM_CONTRACT: string = "BORROWLpSftLendFarm";
const BORROW_STABLE_POOL_CONTRACT: string = "BORROWPool";
const BORROW_STABLE_POOL_FACTORY_CONTRACT: string = "BORROWPoolFactory";

export {
  DEFI_MANAGER_CONTRACT,
  DUTCH_AUCTION_CONTRACT,
  ERC20_INTEREST_FARM_CONTRACT,
  LIQUIDITY_FORGE_CONTRACT,
  LPNFT_CONTRACT,
  LPNFT_STAKE_FARM_CONTRACT,
  LPYIELD_TOKEN_CONTRACT,
  LPBORROW_TOKEN_CONTRACT,
  LPSFT_CONTRACT,
  LPSFT_LEND_FARM_CONTRACT,
  MARKET_STABLE_SWAPPER_CONTRACT,
  NOLPSFT_CONTRACT,
  DEBT_TOKEN_CONTRACT,
  YIELD_LPNFT_STAKE_FARM_CONTRACT,
  YIELD_LPSFT_LEND_FARM_CONTRACT,
  YIELD_MARKET_POOL_CONTRACT,
  YIELD_MARKET_POOL_FACTORY_CONTRACT,
  YIELD_MARKET_POOLER_CONTRACT,
  YIELD_MARKET_SWAPPER_CONTRACT,
  YIELD_TOKEN_CONTRACT,
  BORROW_INTEREST_FARM_CONTRACT,
  BORROW_LPNFT_STAKE_FARM_CONTRACT,
  BORROW_LPSFT_LEND_FARM_CONTRACT,
  BORROW_STABLE_POOL_CONTRACT,
  BORROW_STABLE_POOL_FACTORY_CONTRACT,
  BORROW_STABLE_POOLER_CONTRACT,
  BORROW_STABLE_SWAPPER_CONTRACT,
  BORROW_TOKEN_CONTRACT,
  REVERSE_REPO_CONTRACT,
  THE_RESERVE_CONTRACT,
  UNI_V3_POOL_FACTORY_CONTRACT,
  UNIV3_STAKE_FARM_CONTRACT,
  YIELD_HARVEST_CONTRACT,
};
